site_name: My Docs

nav:
    - index: index.md
    - chapter_exclude_all: chapter_exclude_all.md
    - chapter_exclude_heading2: chapter_exclude_heading2.md
    - dir_chapter_all: dir/dir_chapter_all.md
    - dir_chapter_ignore_heading3: dir/dir_chapter_ignore_heading3.md
    - all_dir: all_dir/all_dir.md
    - all_dir_ignore_heading1: all_dir/all_dir_ignore_heading1.md


theme:
  name: material

plugins:
  - search
  - exclude-search:
      exclude:
        - chapter_exclude_all.md
        - chapter_exclude_heading2.md#single-header-bbex # Always a single # for all header levels.
        - dir_chapter_exclude_all.md
        - dir_chapter_ignore_heading3.md
        - all_dir/*.md
      ignore:
        - dir_chapter_ignore_heading3.md#dir-single-header-ccin
        - all_dir_ignore_heading1.md#alldir-header-aain